% Create a patchMicrostrip antenna
% Generated by MATLAB(R) 23.2 and Antenna Toolbox 23.2.
% Generated on: 21-Mar-2024 10:46:03

%% Antenna Properties 

antennaObject = design(patchMicrostrip, 60*1e9);
antennaObject.Length = 0.0019908;
antennaObject.Width = 0.00083211;
antennaObject.Height = 4.8995e-05;
antennaObject.Substrate.Thickness = 4.8995e-05;
antennaObject.GroundPlaneLength = 0.0023848;
antennaObject.GroundPlaneWidth = 0.0011152;
antennaObject.PatchCenterOffset = [0.00014792, -6.9634e-08];
antennaObject.FeedOffset = [-0.00019916, -0.00014773];
antennaObject.Conductor.Name = 'Aluminium';
antennaObject.Conductor.Conductivity = 8.8902*1e9;
antennaObject.Conductor.Thickness = 0.000762;
% Show
figure;
show(antennaObject) 

%% Antenna Analysis 
% Define plot frequency 
plotFrequency = 60*1e9;
% Define frequency range 
freqRange = (54:0.6:66)*1e9;
% Reference Impedance 
refImpedance = 50;
% pattern
figure;
pattern(antennaObject, plotFrequency)
% elevation
figure;
patternElevation(antennaObject, plotFrequency,0,'Elevation',0:5:360)

