% Input the blender model, then ray trace in model with the isotropic
% antenna.

function rays = raytracing_isotropic(model, pos_tx, f, P_T, pos_rx)

viewer = siteviewer(SceneModel=model);
viewer.Materials;
tx = txsite("cartesian", ...
    "Antenna", 'isotropic', ...
    "AntennaPosition", pos_tx, ...
    'TransmitterFrequency', f, ...
    'TransmitterPower', P_T);

rx = rxsite("cartesian", ...
    "Antenna", 'isotropic', ...
    "AntennaPosition",pos_rx);

show(tx,ShowAntennaHeight=false);
show(rx,ShowAntennaHeight=false);

pm = propagationModel("raytracing", ...
    CoordinateSystem="cartesian", ...
    AngularSeparation=.5, ...
    MaxNumReflections=4, ...
    SurfaceMaterial='concrete', ...
    MaxAbsolutePathLoss=150,...
    MaxRelativePathLoss=Inf,...
    MaxNumDiffractions=1,Method='sbr');
rays = raytrace(tx,rx,pm);
plot(rays{1});

end